# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_uri', models.CharField(max_length=200)),
                ('destination_path', models.CharField(max_length=200)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='jobs.Job')),
            ],
        ),
    ]
