# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collapse', models.BooleanField()),
                ('label', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InputTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_uri', models.CharField(max_length=200)),
                ('destination_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_identifier', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200, null=True)),
                ('uri', models.CharField(max_length=200, null=True)),
                ('user', models.CharField(max_length=200, null=True)),
                ('creation_datetime', models.DateTimeField(null=True)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('help', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('max_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('step', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('type_value', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='cases.FamilyTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_uri', models.CharField(max_length=200)),
                ('destination_path', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('uri', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='case', serialize=False, to='cases.JobTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='scripttemplate',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='cases.JobTemplate'),
        ),
        migrations.AddField(
            model_name='inputtemplate',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='cases.JobTemplate'),
        ),
        migrations.AddField(
            model_name='familytemplate',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='families', to='cases.JobTemplate'),
        ),
    ]
